defmodule IrisServer.Projects.Project do
  use Ecto.Schema
  import Ecto.Changeset

  # Explicit primary key so we expose the `id` field in the schema and ensure
  # it is autogenerated. The DB migration will create this as a serial.
  @primary_key {:id, :id, autogenerate: true}

  schema "projects" do
    field(:name, :string)
    field(:description, :string)
    field(:status, :string)
    field(:stack, :string)
    timestamps()
  end

  def changeset(project, attrs) do
    project
    |> cast(attrs, [
      :name,
      :description,
      :status,
      :stack
    ])
    |> validate_required([:name, :status])
  end
end
